URUT_HARI = [1, 2, 3, 4, 5, 6, 0]


def isi_jadwal(noun):
    return [
        ["Daftar harga layanan", "Jam buka dan hari tutup", "Alamat lengkap dengan tombol peta", "Tombol WhatsApp di setiap layar", "Status buka dihitung dari jam sebenarnya"],
        ["Semua isi paket 1", "Pilih layanan dan %s" % noun, "Pilih tanggal dan jam yang tersedia", "Jam yang sudah penuh tertutup sendiri", "Ringkasan sebelum dikonfirmasi"],
        ["Semua isi paket 2", "Bayar muka saat memesan", "Pilihan QRIS, transfer, atau bayar di tempat", "Nota pemesanan otomatis"],
    ]


def teks_jadwal(jenis, noun):
    return [
        ("Halaman informasi", "Harga layanan, jam buka, alamat, dan tombol WhatsApp. Yang paling cepat jadi dan paling murah.",
         "Kalau yang dibutuhkan hanya supaya orang menemukan %s dan bisa bertanya." % jenis),
        ("Tambah sistem booking", "Pengunjung memilih layanan, %s, tanggal, dan jam sendiri. Tidak perlu bolak-balik WhatsApp." % noun,
         "Kalau jadwal sudah ramai dan pesanan sering bertabrakan."),
        ("Tambah pembayaran", "Pengunjung membayar muka saat memesan, supaya yang memesan tidak hilang begitu saja.",
         "Kalau sering ada yang memesan lalu tidak datang."),
    ]

SALON = dict(
    slug="salon",
    nama="Salon Melati",
    jenis="Salon",
    area="Bandung Wetan, Kota Bandung",
    wa="6281234567890",
    wa_tampil="0812-3456-7890",
    wa_pesan="Halo, saya mau tanya soal booking di Salon Melati.",
    kode="SM",
    noun="Stylist",
    siapa_saja="Terserah, siapa saja",
    siapa_saja_ket="Kami yang menentukan",
    alamat=["Jl. Contoh No. 10", "Bandung Wetan, Kota Bandung 40115", "Sebelah apotek, ada parkir di depan."],
    peta="Jl. Contoh No. 10 Bandung Wetan",
    lead="Potong, warna, dan perawatan rambut dengan harga yang tertera jelas.",
    harga_lead="Panjang dan ketebalan rambut bisa menambah biaya pada layanan warna dan perawatan. Itu dikonfirmasi sebelum dikerjakan.",
    harga_catatan="Layanan pengantin dihitung per paket, termasuk uji tatanan sebelum hari acara.",
    jam_lead="Hari yang tutup ditulis jelas, supaya tidak ada yang datang ke tempat kosong.",
    tip_layanan="Boleh pilih lebih dari satu, total harganya dihitung otomatis. Harga warna dan perawatan bisa bertambah sesuai panjang rambut, dikonfirmasi sebelum dikerjakan.",
    pesan_lead="Tanpa aplikasi dan tanpa formulir panjang. Selesai di halaman ini juga.",
    jam={0: ["10.00", "17.00"], 1: None, 2: ["10.00", "19.00"], 3: ["10.00", "19.00"], 4: ["10.00", "19.00"], 5: ["10.00", "19.00"], 6: ["09.00", "20.00"]},
    grup=[
        ("Potong, cuci, dan tatanan", [
            ("Potong rambut wanita", 75000, 45, ""),
            ("Potong rambut pria", 50000, 30, ""),
            ("Cuci dan blow", 60000, 30, ""),
            ("Catok atau curly", 65000, 30, ""),
            ("Sanggul dan tatanan acara", 200000, 90, ""),
        ]),
        ("Warna dan perawatan", [
            ("Pewarnaan seluruh rambut", 350000, 120, "Perlu konsultasi warna lebih dulu."),
            ("Highlight", 450000, 150, "Waktu menyesuaikan panjang rambut."),
            ("Smoothing", 550000, 180, ""),
            ("Creambath", 90000, 45, ""),
            ("Perawatan kulit kepala", 130000, 45, ""),
        ]),
    ],
    stylist=[
        ("Melati", "Potong dan tatanan", "Sudah 9 tahun menangani potong wanita dan sanggul acara.",
         ["Potong rambut wanita", "Potong rambut pria", "Cuci dan blow", "Catok atau curly", "Sanggul dan tatanan acara"]),
        ("Rina", "Warna dan smoothing", "Khusus pewarnaan dan pelurusan. Konsultasi warna tidak dipungut biaya.",
         ["Pewarnaan seluruh rambut", "Highlight", "Smoothing"]),
        ("Dewi", "Perawatan rambut", "Creambath dan perawatan kulit kepala.",
         ["Creambath", "Perawatan kulit kepala"]),
    ],
    galeri=[("g1", "Area potong dengan cermin"), ("g2", "Meja cermin dan kursi"), ("g4", "Proses potong rambut"), ("g3", "Meja cuci"), ("g5", "Proses pewarnaan rambut"), ("g6", "Ruang depan dan meja resepsionis")],
    galeri_lead="Enam foto suasana dan layanan salon. Di website sungguhan, foto ini diganti foto usaha Anda sendiri.",
    faq=[
        ("Perlu reservasi dulu?", "Disarankan, terutama Sabtu dan Minggu. Bisa lewat halaman ini atau lewat WhatsApp."),
        ("Bisa datang tanpa janji?", "Bisa, dan akan dilayani kalau kursi sedang kosong. Kalau sedang penuh, Anda diberi tahu perkiraan waktu tunggunya sebelum memutuskan menunggu."),
        ("Melayani perawatan pengantin?", "Ya, dihitung per paket, termasuk uji tatanan sebelum hari acara. Kirim tanggal acara untuk mendapat rincian dan ketersediaan."),
        ("Bisa bayar pakai QRIS atau kartu?", "QRIS dan kartu diterima, selain uang tunai."),
        ("Rambut saya pernah diwarnai di tempat lain, bisa ditangani?", "Bisa. Kirim satu foto rambut Anda saat ini lewat WhatsApp, supaya hasil dan biayanya bisa diperkirakan lebih dulu."),
    ],
    galeri_ada=True,
    title_p1="Salon Melati, Bandung Wetan",
    desc_p1="Harga, jam buka, alamat, dan cara menghubungi Salon Melati.",
    desc_book="Pesan layanan, pilih stylist, tanggal, dan jam di Salon Melati.",
    tema="salon",
    gaya="butik",
    hero_foto=("g6", "Ruang salon dengan cermin berornamen putih dan kursi stylist hitam"),
    mode="jadwal",
    label="Salon",
    pendek="Salon",
    ringkas="Potong, warna, dan perawatan rambut, lengkap dengan pilihan stylist dan jam yang masih kosong.",
    lihat="Di demo ini Anda bisa melihat daftar harga layanan, jam buka, galeri, lalu mencoba memesan layanan, stylist, tanggal, dan jam sendiri.",
    contoh_domain="namasalonanda.com",
    kontak="Booking dan pertanyaan:",
    kata_pesan="booking",
    label_item="Layanan dan harga Anda",
    paket_isi=isi_jadwal("stylist"),
    paket_teks=teks_jadwal("salon", "stylist"),
)

BARBER = dict(
    slug="barbershop",
    nama="Barbershop Cukur Rapi",
    jenis="Barbershop",
    area="Coblong, Kota Bandung",
    wa="6287712345678",
    wa_tampil="0877-1234-5678",
    wa_pesan="Bang, saya mau tanya soal booking potong di Cukur Rapi.",
    kode="CR",
    noun="Barber",
    siapa_saja="Terserah, siapa saja",
    siapa_saja_ket="Kami yang menentukan",
    alamat=["Jl. Contoh Raya No. 27, Ruko Blok B", "Coblong, Kota Bandung 40132", "Sebelah warung kopi, di lantai dua."],
    peta="Jl. Contoh Raya No. 27 Coblong Bandung",
    lead="Potong, cukur jenggot, dan styling. Harga tetap, tanpa tambahan.",
    harga_lead="Harga tetap, tidak ada tambahan. Cukur dan rapikan sudah termasuk cuci.",
    harga_catatan="Anak di bawah 10 tahun dapat harga potong anak.",
    jam_lead="Tutup hari Minggu. Sabtu paling ramai, sebaiknya memesan lebih dulu.",
    tip_layanan="Boleh pilih lebih dari satu, total harganya dihitung otomatis. Harga tetap, tidak ada tambahan.",
    pesan_lead="Datang langsung atau memesan lebih dulu, keduanya bisa.",
    jam={0: None, 1: ["11.00", "21.00"], 2: ["11.00", "21.00"], 3: ["11.00", "21.00"], 4: ["11.00", "21.00"], 5: ["11.00", "22.00"], 6: ["10.00", "22.00"]},
    grup=[
        ("Potong", [
            ("Potong biasa", 35000, 30, ""),
            ("Potong dan cuci", 45000, 40, ""),
            ("Potong anak", 30000, 25, ""),
            ("Cukur jenggot", 25000, 20, ""),
        ]),
        ("Perawatan", [
            ("Pomade dan styling", 20000, 15, ""),
            ("Masker rambut", 50000, 30, ""),
            ("Cukur kumis rapi", 15000, 15, ""),
            ("Paket lengkap", 90000, 75, "Potong, cuci, cukur jenggot, dan styling."),
        ]),
    ],
    stylist=[
        ("Andra", "Potong pria dan fade", "Khususnya model fade dan undercut.",
         ["Potong biasa", "Potong dan cuci", "Potong anak", "Cukur jenggot", "Cukur kumis rapi", "Pomade dan styling", "Paket lengkap"]),
        ("Budi", "Cukur jenggot", "Jenggot dan kumis, termasuk perawatan.",
         ["Cukur jenggot", "Cukur kumis rapi", "Paket lengkap"]),
        ("Sandi", "Styling dan pomade", "Penataan dan perawatan rambut.",
         ["Pomade dan styling", "Masker rambut"]),
    ],
    galeri=[("g1", "Ruang potong dengan tiga kursi"), ("g2", "Kursi potong"), ("g3", "Sudut cermin dan rak produk"), ("g4", "Lengkung bata dan kursi potong"), ("g5", "Kursi klasik kulit"), ("g6", "Kursi dan wastafel cuci")],
    galeri_lead="Enam foto suasana barbershop. Di website sungguhan, foto ini diganti foto usaha Anda sendiri.",
    faq=[
        ("Perlu pesan dulu?", "Tidak wajib, tapi Sabtu dan Minggu hampir selalu penuh. Memesan lebih dulu menghemat waktu tunggu."),
        ("Berapa lama satu kali potong?", "Sekitar tiga puluh menit untuk potong biasa, dan sampai satu jam untuk paket lengkap."),
        ("Bisa minta model tertentu dari foto?", "Bisa. Kirim fotonya lewat WhatsApp sebelum datang, supaya waktunya bisa diperkirakan."),
        ("Terima anak kecil?", "Terima, dan ada harga khusus untuk anak di bawah sepuluh tahun."),
    ],
    galeri_ada=True,
    title_p1="Barbershop Cukur Rapi, Coblong",
    desc_p1="Harga, jam buka, alamat, dan cara menghubungi Barbershop Cukur Rapi.",
    desc_book="Pesan layanan, pilih barber, tanggal, dan jam di Barbershop Cukur Rapi.",
    tema="barber",
    mode="jadwal",
    label="Barbershop",
    pendek="Barbershop",
    ringkas="Potong, cukur jenggot, dan styling, lengkap dengan pilihan barber dan jam yang masih kosong.",
    lihat="Di demo ini Anda bisa melihat daftar harga, jam buka, galeri, lalu mencoba memesan layanan, barber, tanggal, dan jam sendiri.",
    contoh_domain="namabarbershopanda.com",
    kontak="Pesan dan pertanyaan:",
    kata_pesan="booking",
    label_item="Layanan dan harga Anda",
    paket_isi=isi_jadwal("barber"),
    paket_teks=teks_jadwal("barbershop", "barber"),
)

SPA = dict(
    galeri_dulu=True,
    slug="spa",
    nama="Kenanga Spa",
    jenis="Spa",
    pendek="Spa",
    label="Spa, massage, dan klinik kecantikan",
    mode="jadwal",
    tema="spa",
    area="Dago, Kota Bandung",
    wa="6281234567891",
    wa_tampil="0812-3456-7891",
    wa_pesan="Halo, saya mau tanya soal booking di Kenanga Spa.",
    kode="KS",
    noun="Terapis",
    siapa_saja="Terserah, siapa saja",
    siapa_saja_ket="Kami yang menentukan",
    alamat=["Jl. Contoh No. 18", "Dago, Kota Bandung 40135", "Di lantai dua, ada parkir di belakang."],
    peta="Jl. Contoh No. 18 Dago Bandung",
    lead="Massage, refleksi, dan perawatan tubuh dengan harga yang tertera jelas.",
    harga_lead="Semua perawatan dihitung per sesi. Durasi tertera di tiap layanan.",
    harga_catatan="Tidak ada tindakan medis di sini. Untuk keluhan kulit, konsultasikan dulu dengan dokter.",
    jam_lead="Buka setiap hari. Datang tanpa janji bisa, tapi memesan lebih dulu lebih pasti.",
    tip_layanan="Boleh pilih lebih dari satu, total harganya dihitung otomatis. Durasi tiap perawatan dijumlahkan.",
    pesan_lead="Tanpa aplikasi dan tanpa formulir panjang. Selesai di halaman ini juga.",
    jam={0: ["10.00", "18.00"], 1: ["10.00", "20.00"], 2: ["10.00", "20.00"], 3: ["10.00", "20.00"], 4: ["10.00", "20.00"], 5: ["10.00", "21.00"], 6: ["09.00", "21.00"]},
    grup=[
        ("Massage", [
            ("Massage badan", 150000, 60, ""),
            ("Massage aromaterapi", 185000, 90, "Minyak pilihan: lavender, serai, atau kenanga."),
            ("Massage tradisional", 130000, 60, ""),
            ("Massage batu hangat", 220000, 90, "Batu hangat di punggung dan kaki."),
        ]),
        ("Refleksi", [
            ("Refleksi kaki", 90000, 45, ""),
            ("Refleksi punggung", 110000, 45, ""),
            ("Refleksi tangan dan kaki", 130000, 60, ""),
        ]),
        ("Perawatan wajah dan tubuh", [
            ("Facial dasar", 150000, 60, "Pembersihan dan masker, tanpa tindakan medis."),
            ("Scrub badan", 140000, 45, ""),
            ("Lulur tradisional", 160000, 60, ""),
            ("Body mask", 175000, 60, ""),
        ]),
    ],
    stylist=[
        ("Sari", "Massage dan refleksi", "Menangani massage badan dan refleksi.",
         ["Massage badan", "Massage aromaterapi", "Massage tradisional", "Refleksi kaki", "Refleksi punggung", "Refleksi tangan dan kaki"]),
        ("Maya", "Perawatan wajah dan tubuh", "Facial dan lulur.",
         ["Facial dasar", "Scrub badan", "Lulur tradisional", "Body mask"]),
        ("Nadia", "Massage batu hangat", "Khusus massage batu hangat dan aromaterapi.",
         ["Massage batu hangat", "Massage aromaterapi"]),
    ],
    galeri=[("g1", "Ruang pijat bersih dengan tempat tidur perawatan"), ("g6", "Bak mandi dengan lilin di atas rak kayu"), ("g2", "Tangan terapis memijat lengan pelanggan"), ("g3", "Minyak esensial dan handuk"), ("g5", "Wadah lulur dan garam mandi"), ("g4", "Lilin dan handuk gulung di ruang perawatan")],
    galeri_lead="Enam foto suasana dan perawatan spa. Di website sungguhan, foto ini diganti foto usaha Anda sendiri.",
    gaya="tenang",
    hero_foto=("g4", "Lilin, handuk gulung, dan botol aroma dengan ranting daun"),
    faq=[
        ("Perlu reservasi dulu?", "Disarankan, apalagi akhir pekan. Bisa lewat halaman ini atau lewat WhatsApp."),
        ("Bisa datang tanpa janji?", "Bisa, dan dilayani kalau ruang perawatan sedang kosong. Kalau penuh, Anda diberi tahu perkiraan waktu tunggunya lebih dulu."),
        ("Apakah ada tindakan medis?", "Tidak ada. Yang ditawarkan hanya massage, refleksi, dan perawatan tubuh. Untuk keluhan kulit, konsultasikan dulu dengan dokter."),
        ("Bisa bayar pakai QRIS atau kartu?", "QRIS dan kartu diterima, selain uang tunai."),
        ("Bisa memilih terapis tertentu?", "Bisa. Kalau terapis pilihan tidak bisa, Anda boleh memilih terapis lain atau Terserah, siapa saja."),
    ],
    title_p1="Kenanga Spa, Dago",
    desc_p1="Harga, jam buka, alamat, dan cara menghubungi Kenanga Spa.",
    desc_book="Pesan perawatan, pilih terapis, tanggal, dan jam di Kenanga Spa.",
    ringkas="Massage, refleksi, facial, dan lulur dengan pilihan terapis dan jadwal sendiri.",
    lihat="Di demo ini Anda bisa melihat daftar perawatan, jam buka, galeri, lalu mencoba memilih terapis, tanggal, dan jam.",
    contoh_domain="namaspaanda.com",
    kontak="Booking dan pertanyaan:",
    kata_pesan="booking",
    label_item="Perawatan dan harga Anda",
    paket_isi=isi_jadwal("terapis"),
    paket_teks=teks_jadwal("spa", "terapis"),
)

PENGINAPAN = dict(
    galeri_dulu=True,
    slug="penginapan",
    nama="Griya Asri Guest House",
    jenis="Penginapan",
    pendek="Penginapan",
    label="Penginapan (guest house, homestay, hotel kecil)",
    mode="inap",
    tema="inap",
    area="Dago, Kota Bandung",
    wa="6281234567892",
    wa_tampil="0812-3456-7892",
    wa_pesan="Halo, saya mau tanya ketersediaan kamar di Griya Asri.",
    kode="GA",
    checkin="14.00",
    checkout="12.00",
    muka=0.3,
    mukaTeks="30 persen",
    bayarNanti="Bayar saat tiba",
    alamat=["Jl. Contoh No. 22", "Dago, Kota Bandung 40135", "Gerbang hijau, ada parkir di halaman."],
    peta="Jl. Contoh No. 22 Dago Bandung",
    lead="Kamar bersih, sarapan, dan lokasi tenang di Dago.",
    harga_lead="Harga per malam, sudah termasuk sarapan. Kamar yang menyediakan air panas tertulis di keterangan.",
    harga_catatan="Harga bisa berbeda saat akhir pekan dan hari libur. Konfirmasi tanggal untuk harga pasti.",
    jam_lead="Resepsionis buka setiap hari. Check-in dan check-out di luar jam itu bisa diatur lewat WhatsApp.",
    jam={0: ["07.00", "22.00"], 1: ["07.00", "22.00"], 2: ["07.00", "22.00"], 3: ["07.00", "22.00"], 4: ["07.00", "22.00"], 5: ["07.00", "22.00"], 6: ["07.00", "22.00"]},
    kamar=[
        ("Kamar Standar", 350000, 2, "Kasur queen, kipas angin, kamar mandi dalam"),
        ("Kamar Deluxe", 450000, 3, "AC, kasur queen, air panas, sarapan untuk dua"),
        ("Kamar Keluarga", 650000, 5, "Dua kamar tidur, AC, dapur kecil, sarapan untuk empat"),
    ],
    galeri=[("g1", "Ruang tamu terang dengan sofa dan cermin rotan"), ("g2", "Kamar tidur dengan seprai putih"), ("g3", "Kamar dengan tempat tidur double dan lampu meja"), ("g4", "Kursi berjemur di tepi kolam"), ("g5", "Kamar mandi dengan bak mandi dan jendela"), ("g6", "Ruang makan teduh dengan tanaman")],
    galeri_lead="Enam foto kamar dan suasana penginapan. Di website sungguhan, foto ini diganti foto usaha Anda sendiri.",
    faq=[
        ("Jam check-in dan check-out?", "Check-in mulai pukul 14.00 dan check-out sebelum pukul 12.00. Di luar jam itu bisa diatur lewat WhatsApp."),
        ("Harga sudah termasuk sarapan?", "Ya, setiap kamar sudah termasuk sarapan. Jumlah porsi mengikuti kapasitas kamar."),
        ("Bisa pesan lebih dari satu kamar?", "Bisa. Pesan lewat WhatsApp untuk jumlah kamar dan tanggalnya, nanti dibantu atur."),
        ("Ada air panas?", "Kamar Deluxe dan Kamar Keluarga menyediakan air panas. Kamar Standar air biasa."),
        ("Bisa membatalkan pesanan?", "Bisa. Kalau uang muka sudah dibayar, uang muka bisa dipakai untuk tanggal lain dengan pemberitahuan lebih dulu."),
    ],
    title_p1="Griya Asri Guest House, Dago",
    desc_p1="Tipe kamar, harga per malam, fasilitas, lokasi, dan cara menghubungi Griya Asri Guest House.",
    desc_book="Pesan kamar, pilih tanggal, jumlah malam, dan tamu di Griya Asri Guest House.",
    ringkas="Tipe kamar, harga per malam, dan cara pesan kamar langsung dari halaman.",
    lihat="Di demo ini Anda bisa melihat tipe kamar dan harga per malam, lalu mencoba memesan kamar, tanggal, dan jumlah malam.",
    contoh_domain="namapenginapananda.com",
    kontak="Reservasi dan pertanyaan:",
    kata_pesan="kamar",
    label_item="Kamar dan harga Anda",
    paket_isi=[
        ["Tipe kamar dan harga per malam", "Fasilitas tiap kamar", "Lokasi dan peta", "Tombol WhatsApp di setiap layar", "Galeri foto kamar"],
        ["Semua isi paket 1", "Pilih tipe kamar", "Pilih tanggal dan jumlah malam", "Perkiraan harga otomatis", "Ringkasan sebelum dikonfirmasi"],
        ["Semua isi paket 2", "Bayar uang muka 30 persen", "Pilihan QRIS, transfer, atau bayar saat tiba", "Nota pemesanan otomatis"],
    ],
    paket_teks=[
        ("Halaman informasi", "Tipe kamar, harga per malam, fasilitas, lokasi, dan tombol WhatsApp.", "Kalau tamu perlu tahu kamar dan harga sebelum menghubungi."),
        ("Tambah sistem booking", "Tamu memilih kamar, tanggal, jumlah malam, dan jumlah tamu sendiri.", "Kalau pesanan kamar sering dicatat manual dan sering bentrok."),
        ("Tambah pembayaran", "Tamu membayar uang muka saat memesan, supaya pesanan kamar tidak hilang.", "Kalau sering ada tamu yang memesan lalu tidak jadi datang."),
    ],
)

KATERING = dict(
    slug="katering",
    nama="Dapur Bu Sari",
    jenis="Katering",
    pendek="Katering",
    label="Katering dan toko kue",
    mode="pesan",
    tema="pesan",
    area="Kota Bandung",
    wa="6281234567893",
    wa_tampil="0812-3456-7893",
    wa_pesan="Halo, saya mau tanya soal pesanan katering di Dapur Bu Sari.",
    kode="DB",
    ongkir=20000,
    areaAntar="Diantar dalam kota, radius 10 km.",
    tempatAmbil="Jl. Contoh No. 5, Kota Bandung",
    muka=0.5,
    mukaTeks="50 persen",
    bayarNanti="Bayar saat serah terima",
    alamat=["Jl. Contoh No. 5", "Kota Bandung 40115", "Dapur produksi, pesanan diambil di depan."],
    peta="Jl. Contoh No. 5 Bandung",
    lead="Nasi box, tumpeng, dan kue untuk acara, dengan harga per porsi yang jelas.",
    harga_lead="Harga per porsi, buah, atau toples. Pesanan ada jumlah minimalnya, tertera di tiap menu.",
    harga_catatan="Harga belum termasuk ongkos antar. Pesanan besar sebaiknya dipesan lebih awal.",
    jam_lead="Menerima pesanan setiap hari kerja. Untuk akhir pekan, pesan lebih awal.",
    jam={0: None, 1: ["08.00", "18.00"], 2: ["08.00", "18.00"], 3: ["08.00", "18.00"], 4: ["08.00", "18.00"], 5: ["08.00", "18.00"], 6: ["08.00", "16.00"]},
    menu=[
        ("Nasi box", [
            {"nama": "Nasi box ayam bakar", "harga": 35000, "min": 10, "maks": 100, "satuan": "box", "ket": "Nasi, ayam bakar, lalap, sambal", "lead": 2},
            {"nama": "Nasi box rendang", "harga": 40000, "min": 10, "maks": 100, "satuan": "box", "ket": "Nasi, rendang, sayur, kerupuk", "lead": 2},
            {"nama": "Nasi box vegetarian", "harga": 30000, "min": 10, "maks": 100, "satuan": "box", "ket": "Tahu, tempe, sayur, sambal", "lead": 3},
        ]),
        ("Tumpeng", [
            {"nama": "Tumpeng mini", "harga": 450000, "min": 1, "maks": 10, "satuan": "buah", "ket": "Untuk 8 sampai 10 orang", "lead": 3},
            {"nama": "Tumpeng besar", "harga": 850000, "min": 1, "maks": 5, "satuan": "buah", "ket": "Untuk 20 sampai 25 orang", "lead": 4},
        ]),
        ("Kue ulang tahun", [
            {"nama": "Kue ulang tahun 20 cm", "harga": 280000, "min": 1, "maks": 10, "satuan": "buah", "ket": "Bisa tulis nama di atas kue", "lead": 3},
            {"nama": "Kue ulang tahun 24 cm", "harga": 380000, "min": 1, "maks": 10, "satuan": "buah", "ket": "Bisa tulis nama di atas kue", "lead": 3},
        ]),
        ("Kue kering", [
            {"nama": "Kue kering nastar", "harga": 90000, "min": 2, "maks": 50, "satuan": "toples", "ket": "Isi sekitar 500 gram", "lead": 2},
            {"nama": "Kue kering kastengel", "harga": 100000, "min": 2, "maks": 50, "satuan": "toples", "ket": "Isi sekitar 500 gram", "lead": 2},
        ]),
    ],
    galeri=[("g1", "Tumpeng nasi kuning dengan lauk dan sayuran"), ("g2", "Boks makanan siap antar di atas meja kayu"), ("g3", "Hidangan prasmanan dalam wadah saji"), ("g4", "Kue ulang tahun dengan lilin"), ("g5", "Kue mini di atas rak saji bertingkat"), ("g6", "Pai dan roti kecil di atas piring")],
    galeri_lead="Enam foto menu dan hasil masakan. Di website sungguhan, foto ini diganti foto usaha Anda sendiri.",
    faq=[
        ("Berapa minimal pesanan?", "Nasi box minimal 10, tumpeng dan kue minimal 1, kue kering minimal 2 toples. Tertera di tiap menu."),
        ("Berapa lama sebelumnya harus pesan?", "Nasi box 2 sampai 3 hari sebelumnya, tumpeng dan kue 3 sampai 4 hari sebelumnya. Di tiap menu tertulis perkiraannya."),
        ("Bisa diantar?", "Bisa, diantar dalam kota. Ada ongkos antar. Untuk luar kota bisa diatur lewat WhatsApp."),
        ("Bisa minta tanpa bahan tertentu?", "Bisa. Tulis di kolom catatan, misalnya tanpa kacang atau tanpa pedas, nanti dikonfirmasi."),
        ("Ada tulisan di kue?", "Bisa. Tulis teksnya di kolom catatan saat memesan kue."),
    ],
    title_p1="Dapur Bu Sari, katering dan kue",
    desc_p1="Menu, harga, jumlah minimal, dan cara memesan katering Dapur Bu Sari.",
    desc_book="Pesan katering dan kue, pilih menu, tanggal, dan cara terima di Dapur Bu Sari.",
    ringkas="Menu katering dan kue dengan jumlah, tanggal, dan cara terima yang bisa dipilih.",
    lihat="Di demo ini Anda bisa melihat menu dan harga, lalu mencoba memesan jumlah, tanggal, dan cara terima.",
    contoh_domain="namakateringanda.com",
    kontak="Pesanan dan pertanyaan:",
    kata_pesan="hidangan",
    label_item="Menu dan harga Anda",
    paket_isi=[
        ["Daftar menu dan harga", "Jumlah minimal tiap menu", "Jam dan area antar", "Tombol WhatsApp di setiap layar", "Galeri foto menu"],
        ["Semua isi paket 1", "Pilih menu dan jumlah", "Pilih tanggal dan cara terima", "Total harga otomatis", "Ringkasan sebelum dikonfirmasi"],
        ["Semua isi paket 2", "Bayar uang muka 50 persen", "Pilihan QRIS, transfer, atau bayar saat serah terima", "Nota pesanan otomatis"],
    ],
    paket_teks=[
        ("Halaman informasi", "Menu, harga, jumlah minimal, jam, dan area antar.", "Kalau pembeli hanya perlu melihat menu dan bertanya."),
        ("Tambah sistem pemesanan", "Pembeli memilih menu, jumlah, tanggal, dan cara terima sendiri.", "Kalau pesanan sering dicatat lewat percakapan yang panjang."),
        ("Tambah pembayaran", "Pembeli membayar uang muka saat memesan, supaya pesanan lebih pasti.", "Kalau sering ada pesanan besar yang batal."),
    ],
)

GALERI_INAP = [("Tipe kamar", [("Kamar Standar", 350000, "Maks. 2 tamu, per malam"), ("Kamar Deluxe", 450000, "Maks. 3 tamu, per malam"), ("Kamar Keluarga", 650000, "Maks. 5 tamu, per malam")])]
PENGINAPAN["grup"] = GALERI_INAP
KATERING["grup"] = [(g, [(it["nama"], it["harga"], it["ket"]) for it in items]) for g, items in KATERING["menu"]]

USAHA = [SALON, BARBER, SPA, PENGINAPAN, KATERING]
USAHABY = {u["slug"]: u for u in USAHA}
