URUT_HARI = [1, 2, 3, 4, 5, 6, 0]

SALON = dict(
    slug="salon",
    nama="Salon Melati",
    jenis="Salon",
    area="Bandung Wetan, Kota Bandung",
    wa="6281234567890",
    wa_tampil="0812-3456-7890",
    wa_pesan="Halo, saya mau tanya soal booking di Salon Melati.",
    kode="SM",
    noun="Stylist",
    siapa_saja="Terserah, siapa saja",
    siapa_saja_ket="Kami yang menentukan",
    alamat=["Jl. Contoh No. 10", "Bandung Wetan, Kota Bandung 40115", "Sebelah apotek, ada parkir di depan."],
    peta="Jl. Contoh No. 10 Bandung Wetan",
    lead="Potong, warna, dan perawatan rambut dengan harga yang tertera jelas.",
    harga_lead="Panjang dan ketebalan rambut bisa menambah biaya pada layanan warna dan perawatan. Itu dikonfirmasi sebelum dikerjakan.",
    harga_catatan="Layanan pengantin dihitung per paket, termasuk uji tatanan sebelum hari acara.",
    jam_lead="Hari yang tutup ditulis jelas, supaya tidak ada yang datang ke tempat kosong.",
    tip_layanan="Boleh pilih lebih dari satu, total harganya dihitung otomatis. Harga warna dan perawatan bisa bertambah sesuai panjang rambut, dikonfirmasi sebelum dikerjakan.",
    pesan_lead="Tanpa aplikasi dan tanpa formulir panjang. Selesai di halaman ini juga.",
    jam={0: ["10.00", "17.00"], 1: None, 2: ["10.00", "19.00"], 3: ["10.00", "19.00"], 4: ["10.00", "19.00"], 5: ["10.00", "19.00"], 6: ["09.00", "20.00"]},
    grup=[
        ("Potong, cuci, dan tatanan", [
            ("Potong rambut wanita", 75000, 45, ""),
            ("Potong rambut pria", 50000, 30, ""),
            ("Cuci dan blow", 60000, 30, ""),
            ("Catok atau curly", 65000, 30, ""),
            ("Sanggul dan tatanan acara", 200000, 90, ""),
        ]),
        ("Warna dan perawatan", [
            ("Pewarnaan seluruh rambut", 350000, 120, "Perlu konsultasi warna lebih dulu."),
            ("Highlight", 450000, 150, "Waktu menyesuaikan panjang rambut."),
            ("Smoothing", 550000, 180, ""),
            ("Creambath", 90000, 45, ""),
            ("Perawatan kulit kepala", 130000, 45, ""),
        ]),
    ],
    stylist=[
        ("Melati", "Potong dan tatanan", "Sudah 9 tahun menangani potong wanita dan sanggul acara.",
         ["Potong rambut wanita", "Potong rambut pria", "Cuci dan blow", "Catok atau curly", "Sanggul dan tatanan acara"]),
        ("Rina", "Warna dan smoothing", "Khusus pewarnaan dan pelurusan. Konsultasi warna tidak dipungut biaya.",
         ["Pewarnaan seluruh rambut", "Highlight", "Smoothing"]),
        ("Dewi", "Perawatan rambut", "Creambath dan perawatan kulit kepala.",
         ["Creambath", "Perawatan kulit kepala"]),
    ],
    galeri=[("g6", "Ruang depan dan meja resepsionis"), ("g1", "Area potong dengan cermin"), ("g2", "Meja cermin dan kursi"), ("g3", "Meja cuci"), ("g4", "Proses potong rambut"), ("g5", "Proses pewarnaan rambut")],
    galeri_lead="Enam foto suasana dan layanan salon. Di website sungguhan, foto ini diganti foto usaha Anda sendiri.",
    faq=[
        ("Perlu reservasi dulu?", "Disarankan, terutama Sabtu dan Minggu. Bisa lewat halaman ini atau lewat WhatsApp."),
        ("Bisa datang tanpa janji?", "Bisa, dan akan dilayani kalau kursi sedang kosong. Kalau sedang penuh, Anda diberi tahu perkiraan waktu tunggunya sebelum memutuskan menunggu."),
        ("Melayani perawatan pengantin?", "Ya, dihitung per paket, termasuk uji tatanan sebelum hari acara. Kirim tanggal acara untuk mendapat rincian dan ketersediaan."),
        ("Bisa bayar pakai QRIS atau kartu?", "QRIS dan kartu diterima, selain uang tunai."),
        ("Rambut saya pernah diwarnai di tempat lain, bisa ditangani?", "Bisa. Kirim satu foto rambut Anda saat ini lewat WhatsApp, supaya hasil dan biayanya bisa diperkirakan lebih dulu."),
    ],
    galeri_ada=True,
    title_p1="Salon Melati, Bandung Wetan",
    desc_p1="Harga, jam buka, alamat, dan cara menghubungi Salon Melati.",
    desc_book="Pesan layanan, pilih stylist, tanggal, dan jam di Salon Melati.",
    tema="salon",
)

BARBER = dict(
    slug="barbershop",
    nama="Barbershop Cukur Rapi",
    jenis="Barbershop",
    area="Coblong, Kota Bandung",
    wa="6287712345678",
    wa_tampil="0877-1234-5678",
    wa_pesan="Bang, saya mau tanya soal booking potong di Cukur Rapi.",
    kode="CR",
    noun="Barber",
    siapa_saja="Terserah, siapa saja",
    siapa_saja_ket="Kami yang menentukan",
    alamat=["Jl. Contoh Raya No. 27, Ruko Blok B", "Coblong, Kota Bandung 40132", "Sebelah warung kopi, di lantai dua."],
    peta="Jl. Contoh Raya No. 27 Coblong Bandung",
    lead="Potong, cukur jenggot, dan styling. Harga tetap, tanpa tambahan.",
    harga_lead="Harga tetap, tidak ada tambahan. Cukur dan rapikan sudah termasuk cuci.",
    harga_catatan="Anak di bawah 10 tahun dapat harga potong anak.",
    jam_lead="Tutup hari Minggu. Sabtu paling ramai, sebaiknya memesan lebih dulu.",
    tip_layanan="Boleh pilih lebih dari satu, total harganya dihitung otomatis. Harga tetap, tidak ada tambahan.",
    pesan_lead="Datang langsung atau memesan lebih dulu, keduanya bisa.",
    jam={0: None, 1: ["11.00", "21.00"], 2: ["11.00", "21.00"], 3: ["11.00", "21.00"], 4: ["11.00", "21.00"], 5: ["11.00", "22.00"], 6: ["10.00", "22.00"]},
    grup=[
        ("Potong", [
            ("Potong biasa", 35000, 30, ""),
            ("Potong dan cuci", 45000, 40, ""),
            ("Potong anak", 30000, 25, ""),
            ("Cukur jenggot", 25000, 20, ""),
        ]),
        ("Perawatan", [
            ("Pomade dan styling", 20000, 15, ""),
            ("Masker rambut", 50000, 30, ""),
            ("Cukur kumis rapi", 15000, 15, ""),
            ("Paket lengkap", 90000, 75, "Potong, cuci, cukur jenggot, dan styling."),
        ]),
    ],
    stylist=[
        ("Andra", "Potong pria dan fade", "Khususnya model fade dan undercut.",
         ["Potong biasa", "Potong dan cuci", "Potong anak", "Cukur jenggot", "Cukur kumis rapi", "Pomade dan styling", "Paket lengkap"]),
        ("Budi", "Cukur jenggot", "Jenggot dan kumis, termasuk perawatan.",
         ["Cukur jenggot", "Cukur kumis rapi", "Paket lengkap"]),
        ("Sandi", "Styling dan pomade", "Penataan dan perawatan rambut.",
         ["Pomade dan styling", "Masker rambut"]),
    ],
    galeri=[("g1", "Ruang potong dengan tiga kursi"), ("g2", "Kursi potong"), ("g3", "Sudut cermin dan rak produk"), ("g4", "Lengkung bata dan kursi potong"), ("g5", "Kursi klasik kulit"), ("g6", "Kursi dan wastafel cuci")],
    galeri_lead="Enam foto suasana barbershop. Di website sungguhan, foto ini diganti foto usaha Anda sendiri.",
    faq=[
        ("Perlu pesan dulu?", "Tidak wajib, tapi Sabtu dan Minggu hampir selalu penuh. Memesan lebih dulu menghemat waktu tunggu."),
        ("Berapa lama satu kali potong?", "Sekitar tiga puluh menit untuk potong biasa, dan sampai satu jam untuk paket lengkap."),
        ("Bisa minta model tertentu dari foto?", "Bisa. Kirim fotonya lewat WhatsApp sebelum datang, supaya waktunya bisa diperkirakan."),
        ("Terima anak kecil?", "Terima, dan ada harga khusus untuk anak di bawah sepuluh tahun."),
    ],
    galeri_ada=True,
    title_p1="Barbershop Cukur Rapi, Coblong",
    desc_p1="Harga, jam buka, alamat, dan cara menghubungi Barbershop Cukur Rapi.",
    desc_book="Pesan layanan, pilih barber, tanggal, dan jam di Barbershop Cukur Rapi.",
    tema="barber",
)
